name: Trigger tests
on:
  # push:
  #   branches:
  #     - '**'
  #   paths-ignore:
  #     - 'docs/**'
  #     - '**.md'
  #     - '.vscode/**'
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PUBLIC_REPO_PAT }}
          repository: ReactUnity/core
          event-type: run-tests
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
